[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remapping = []

[rpc_endpoints]
base-sepolia = "${BASE_SEPOLIA_RPC_URL}"

[etherscan]
base-sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=84532" }